kind: pipeline
name: default

steps:
  - name: build
    image: golang:1.11
    environment:
      GO111MODULES: on
      CGO_ENABLED: 0
    commands:
      - go build -ldflags '-w -extldflags "-static"' -o plafws ./cmd/

  - name: test
    image: golang:1.11
    environment:
      GO111MODULES: on
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ""
      POSTGRES_ADDR: "database:26257"
    commands:
      - go test -timeout 30s ./...

  # This is broken right now
  - name: docker-ci
    image: plugins/docker:17.12
    repo: misaki.packetlostandfound.us:5005/chiefnoah/packetlostandfoundws
    registry: misaki.packetlostandfound.us:5005
    # username: ${docker_username}
    # password: ${docker_password}
    when:
      event: [deployment, push]
      branches: [master, develop]

services:
  - name: database
    image: cockroachdb/cockroach:v2.1.0
    command: [ "start", "--insecure" ]